"""init schema

Revision ID: d6e633470779
Revises: 
Create Date: 2026-09-30 15:28:20.948823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e633470779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_players', sa.SmallInteger(), nullable=False),
    sa.Column('max_players', sa.SmallInteger(), nullable=False),
    sa.Column('playtime_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('daily_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cover_key', sa.String(length=255), nullable=True),
    sa.CheckConstraint('daily_price >= 0', name=op.f('ck_board_games_daily_price')),
    sa.CheckConstraint('deposit_price >= 0', name=op.f('ck_board_games_deposit_price')),
    sa.CheckConstraint('max_players >= min_players', name=op.f('ck_board_games_max_players')),
    sa.CheckConstraint('min_players > 0', name=op.f('ck_board_games_min_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_games'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('email', name=op.f('uq_clients_email'))
    )
    op.create_table('pickup_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_points'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'MANAGER' AND pickup_point_id IS NOT NULL) OR (role <> 'MANAGER' AND pickup_point_id IS NULL)", name=op.f('ck_employees_manager_requires_point')),
    sa.CheckConstraint("role IN ('COURIER','MANAGER','ADMIN')", name=op.f('ck_employees_role')),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickup_points.id'], name=op.f('fk_employees_pickup_point_id_pickup_points'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('email', name=op.f('uq_employees_email'))
    )
    op.create_table('game_categories',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_game_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['board_games.id'], name=op.f('fk_game_categories_game_id_board_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'category_id', name=op.f('pk_game_categories'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_categories')
    op.drop_table('employees')
    op.drop_table('pickup_points')
    op.drop_table('clients')
    op.drop_table('categories')
    op.drop_table('board_games')
    # ### end Alembic commands ###
